export const EVENTS_FETCH_PENDING = "EVENTS_FETCH_PENDING";
export const EVENTS_FETCH_SUCCESS = "EVENTS_FETCH_SUCCESS";
export const EVENTS_FETCH_MORE = "EVENTS_FETCH_MORE";

export const PERFORMERS_FETCH_PENDING = "PERFORMERS_FETCH_PENDING";
export const PERFORMERS_FETCH_SUCCESS = "PERFORMERS_FETCH_SUCCESS";
export const PERFORMERS_FETCH_MORE = "PERFORMERS_FETCH_MORE";

export const EVENT_DETAILS_FETCH_PENDING = "EVENT_DETAILS_FETCH_PENDING";
export const EVENT_DETAILS_FETCH_SUCCESS = "EVENT_DETAILS_FETCH_SUCCESS";
